/**
 * Simulates an AI service to generate summaries for news articles.
 * Uses a heuristic approach to extract key sentences since we are offline/local.
 */

export const generateSummary = async (text, title, language = 'tr') => {
    // Simulate network delay for "AI thinking" effect
    await new Promise(resolve => setTimeout(resolve, 1500));

    if (!text) return language === 'en' ? "No content to summarize." : "Özetlenecek içerik bulunamadı.";

    // Simple cleaner to remove HTML tags if any remain
    const cleanText = text.replace(/<[^>]*>/g, '').trim();

    // Split into sentences
    const sentences = cleanText.match(/[^.!?]+[.!?]+/g) || [cleanText];

    // Heuristic:
    // 1. Always include the first sentence (usually the lead).
    // 2. Look for sentences with key phrases like "önemli", "sonuç", "belirtti".
    // 3. Limit to 3 items.

    const summaryPoints = [];

    // 1. Lead sentence
    if (sentences.length > 0) {
        summaryPoints.push(sentences[0].trim());
    }

    // 2. Key info extraction (simple keyword matching)
    const keywords = ['açıkladı', 'duyurdu', 'nedeniyle', 'sonucunda', 'ancak', 'yeni', 'ilk'];

    for (let i = 1; i < sentences.length; i++) {
        if (summaryPoints.length >= 3) break;

        const sentence = sentences[i].trim();
        // Skip if too short or too long
        if (sentence.length < 20 || sentence.length > 200) continue;

        const hasKeyword = keywords.some(k => sentence.toLowerCase().includes(k));
        if (hasKeyword) {
            summaryPoints.push(sentence);
        }
    }

    // If not enough points, just take the next ones
    let i = 1;
    while (summaryPoints.length < 3 && i < sentences.length) {
        const sentence = sentences[i].trim();
        if (!summaryPoints.includes(sentence) && sentence.length > 30) {
            summaryPoints.push(sentence);
        }
        i++;
    }

    // For English simulation, since we can't truly translate offline without a heavy library,
    // we will wrap the content or provide a mock response if it's just a demo.
    // However, to keep it functional but honest:
    if (language === 'en') {
        return {
            points: summaryPoints.map(p => `[TR Source] ${p}`), // Tagging it as source language
            tone: 'neutral',
            disclaimer: 'Summary generated by AI (English translation unavailable in offline mode).',
            title: 'AI Summary'
        };
    }

    return {
        points: summaryPoints,
        tone: 'neutral',
        disclaimer: 'Bu özet yapay zeka tarafından otomatik oluşturulmuştur.',
        title: 'AI Özeti'
    };
};
